name: Lint and Test
run-name: ${{ github.actor }} running Lint and Test action by ${{ github.event_name }}
on:
  push:
    branches:
      - '!master'
      - '!main'
  pull_request:
    branches: ['master', 'main']
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
